services:
  ml-base:
    env_file: .env
    restart: always
    container_name: ml-base-dev
    image: ghcr.io/${GIT_NAME}/ml-base:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    volumes:
      - .:/workspace/ml-base
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "test -s `which nvidia-smi` && nvidia-smi || exit 1"]
      start_period: 1s
      interval: 20s
      timeout: 5s
      retries: 2