services:
  ray-head:
    image: ghcr.io/${GIT_NAME}/ml-base:latest  # Use the same base image as project container
    container_name: ray-head
    network_mode: host
    command: >
      zsh -c "
      ray start --head \
      --include-dashboard=true \
      --dashboard-host=0.0.0.0 \
      --dashboard-port=8265 \
      --port=6379 \
      --ray-client-server-port=10001 \
      --node-ip-address=0.0.0.0 \
      --block"