# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.error_code import ErrorCode

class TestErrorCode(unittest.TestCase):
    """ErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorCode(self):
        """Test ErrorCode"""
        # inst = ErrorCode()

if __name__ == '__main__':
    unittest.main()
