# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.instance_type import InstanceType

class TestInstanceType(unittest.TestCase):
    """InstanceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceType:
        """Test InstanceType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceType`
        """
        model = InstanceType()
        if include_optional:
            return InstanceType(
                name = 'gpu_1x_a100',
                description = '1x RTX A100 (24 GB)',
                gpu_description = 'RTX A100 (24 GB)',
                price_cents_per_hour = 110,
                specs = openapi_client.models.instance_type_specs.instanceType_specs(
                    vcpus = 24, 
                    memory_gib = 800, 
                    storage_gib = 512, 
                    gpus = 4, )
            )
        else:
            return InstanceType(
                name = 'gpu_1x_a100',
                description = '1x RTX A100 (24 GB)',
                gpu_description = 'RTX A100 (24 GB)',
                price_cents_per_hour = 110,
                specs = openapi_client.models.instance_type_specs.instanceType_specs(
                    vcpus = 24, 
                    memory_gib = 800, 
                    storage_gib = 512, 
                    gpus = 4, ),
        )
        """

    def testInstanceType(self):
        """Test InstanceType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
