# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.error_response_body import ErrorResponseBody

class TestErrorResponseBody(unittest.TestCase):
    """ErrorResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponseBody:
        """Test ErrorResponseBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponseBody`
        """
        model = ErrorResponseBody()
        if include_optional:
            return ErrorResponseBody(
                error = openapi_client.models.error.error(
                    code = 'global/unknown', 
                    message = 'API key is invalid, expired, or deleted.', 
                    suggestion = 'Create a new API key and try again.', ),
                field_errors = {
                    'key' : openapi_client.models.error.error(
                        code = 'global/unknown', 
                        message = 'API key is invalid, expired, or deleted.', 
                        suggestion = 'Create a new API key and try again.', )
                    }
            )
        else:
            return ErrorResponseBody(
                error = openapi_client.models.error.error(
                    code = 'global/unknown', 
                    message = 'API key is invalid, expired, or deleted.', 
                    suggestion = 'Create a new API key and try again.', ),
        )
        """

    def testErrorResponseBody(self):
        """Test ErrorResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
