# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_file_systems200_response import ListFileSystems200Response

class TestListFileSystems200Response(unittest.TestCase):
    """ListFileSystems200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListFileSystems200Response:
        """Test ListFileSystems200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListFileSystems200Response`
        """
        model = ListFileSystems200Response()
        if include_optional:
            return ListFileSystems200Response(
                data = [
                    openapi_client.models.file_system.fileSystem(
                        id = '0920582c7ff041399e34823a0be62547', 
                        name = 'shared-fs', 
                        created = '2023-02-24T20:48:56+00:00', 
                        created_by = openapi_client.models.user.user(
                            id = '0920582c7ff041399e34823a0be62549', 
                            email = 'teammate@example.com', 
                            status = 'active', ), 
                        mount_point = '/home/ubuntu/shared-fs', 
                        region = openapi_client.models.region.region(
                            name = 'us-tx-1', 
                            description = 'Austin, Texas', ), 
                        is_in_use = True, 
                        bytes_used = 2147483648, )
                    ]
            )
        else:
            return ListFileSystems200Response(
                data = [
                    openapi_client.models.file_system.fileSystem(
                        id = '0920582c7ff041399e34823a0be62547', 
                        name = 'shared-fs', 
                        created = '2023-02-24T20:48:56+00:00', 
                        created_by = openapi_client.models.user.user(
                            id = '0920582c7ff041399e34823a0be62549', 
                            email = 'teammate@example.com', 
                            status = 'active', ), 
                        mount_point = '/home/ubuntu/shared-fs', 
                        region = openapi_client.models.region.region(
                            name = 'us-tx-1', 
                            description = 'Austin, Texas', ), 
                        is_in_use = True, 
                        bytes_used = 2147483648, )
                    ],
        )
        """

    def testListFileSystems200Response(self):
        """Test ListFileSystems200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
