# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_ssh_key(self) -> None:
        """Test case for add_ssh_key

        Add SSH key
        """
        pass

    def test_delete_ssh_key(self) -> None:
        """Test case for delete_ssh_key

        Delete SSH key
        """
        pass

    def test_get_instance(self) -> None:
        """Test case for get_instance

        List details of a specific instance
        """
        pass

    def test_instance_types(self) -> None:
        """Test case for instance_types

        Retrieve list of offered instance types
        """
        pass

    def test_launch_instance(self) -> None:
        """Test case for launch_instance

        Launch instances
        """
        pass

    def test_list_file_systems(self) -> None:
        """Test case for list_file_systems

        List file systems
        """
        pass

    def test_list_instances(self) -> None:
        """Test case for list_instances

        List running instances
        """
        pass

    def test_list_ssh_keys(self) -> None:
        """Test case for list_ssh_keys

        List SSH keys
        """
        pass

    def test_restart_instance(self) -> None:
        """Test case for restart_instance

        Restart instances
        """
        pass

    def test_terminate_instance(self) -> None:
        """Test case for terminate_instance

        Terminate an instance
        """
        pass


if __name__ == '__main__':
    unittest.main()
