# coding: utf-8

"""
    Lambda Cloud API

    API for interacting with the Lambda GPU Cloud

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.instance_types200_response import InstanceTypes200Response

class TestInstanceTypes200Response(unittest.TestCase):
    """InstanceTypes200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceTypes200Response:
        """Test InstanceTypes200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceTypes200Response`
        """
        model = InstanceTypes200Response()
        if include_optional:
            return InstanceTypes200Response(
                data = {"gpu_1x_a100":{"instance_type":{"name":"gpu_1x_a100","description":"1x RTX A100 (24 GB)","price_cents_per_hour":"80","specs":{"vcpus":24,"memory_gib":800,"storage_gib":512}},"regions_with_capacity_available":[{"name":"us-tx-1","description":"Austin, Texas"}]},"gpu_4x_a6000":{"instance_type":{"name":"gpu_4x_a6000","description":"4x RTX 6000 (24 GB)","price_cents_per_hour":"110","specs":{"vcpus":24,"memory_gib":800,"storage_gib":512}},"regions_with_capacity_available":[{"name":"us-phoenix-1","description":"Phoenix, Arizona"}]}}
            )
        else:
            return InstanceTypes200Response(
                data = {"gpu_1x_a100":{"instance_type":{"name":"gpu_1x_a100","description":"1x RTX A100 (24 GB)","price_cents_per_hour":"80","specs":{"vcpus":24,"memory_gib":800,"storage_gib":512}},"regions_with_capacity_available":[{"name":"us-tx-1","description":"Austin, Texas"}]},"gpu_4x_a6000":{"instance_type":{"name":"gpu_4x_a6000","description":"4x RTX 6000 (24 GB)","price_cents_per_hour":"110","specs":{"vcpus":24,"memory_gib":800,"storage_gib":512}},"regions_with_capacity_available":[{"name":"us-phoenix-1","description":"Phoenix, Arizona"}]}},
        )
        """

    def testInstanceTypes200Response(self):
        """Test InstanceTypes200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
